### ISSUE TITLE
Move API docs to github pages

### ISSUE THREAD

**Issue by smilindave26** [openziti/ziti-sdk-swift#153]
- deploy to local repo github pages
- get it into Docusaurus

**Comment by gajrajgchouhan** [comment]
Hi Dave, I would like to look into this issue. Can you please tell how are the documents are made currently?

**Comment by smilindave26** [comment]
Great!  The docs are currently built using `jazzy` in a GitHub action, then uploaded as artifacts on the action.  Have a look at https://github.com/openziti/ziti-sdk-swift/blob/49e7bf4931d2ed5053fe68adb9addadd05d65eef/.github/workflows/CI.yml#L83

Don't worry about the Docusaurus note - just getting them into this repo's gihub-pages is enough.  I'll probably need to configure the repo for you, How I do that will depend on the way you implement (repo asks to choose between deploying from a branch or via GitHub action - we'd want to automatically deploy thru a GitHub Action either way)

**Comment by gajrajgchouhan** [comment]
Hey Dave,
I saw the `yml` file and it looks like the docs are zipped into a `ziti-sdk-swift-docs.tgz` file. 
Please correct me if I am wrong but then we only need to probably unzip the file and I am assuming it contains some kind of `index.html` file which can then be deployed to GitHub pages. In that case, can I get the `tgz` file? I will probably try to deploy it to my personal GitHub page link (and they use similar steps in this repo?) or if you have an existing pipeline that does the deployment of such kinds of docs then maybe we can use that directly?

**Comment by smilindave26** [comment]
Looks like you are on the right track.  That `tgz` is uploaded as on artifact for each release, latest here: https://github.com/openziti/ziti-sdk-swift/releases/latest.  I'd go about this the same way you suggest, mainly because I'd first need to learn how to do the deploy.  Currently, the [Latest Release](https://github.com/openziti/ziti-sdk-swift/blob/49e7bf4931d2ed5053fe68adb9addadd05d65eef/.github/workflows/CI.yml#L116) step is the place where we move the artifact to the release.  We have a different pipeline (in `ziti-docs`) that moves them to [here](https://openziti.github.io/docusaurus/api/swift/index.html) that we'll update once this issue is completed

**Comment by gajrajgchouhan** [comment]
Hi Dave, I am a bit confused about the resolution of the issue. The docs are already deployed fine, what are we supposed to change here?

**Comment by smilindave26** [comment]
It's really close - the docs are all generated, but we want them deployed to https://openziti.github.io/ziti-sdk-swift/ (the "GitHub Pages" link for this repo) instead of just attached as an artifact to the release.

**Comment by smilindave26** [comment]
Thanks - PR was accepted, closing the issue.
