### ISSUE TITLE
Whether socket interception is supported

### ISSUE THREAD

**Issue by five131415** [openziti/ziti-sdk-swift#168]
Does it only support the interception of http and https

Whether socket interception is supported

**Comment by smilindave26** [comment]
"interception" is a feature of https://github.com/openziti/ziti-tunnel-apple, which implements an Apple NetworkExtension and uses this SDK.  It can intercept IP addresses, route the traffic over Ziti, and intercept DNS requests to return addresses that are then routed over Ziti.

You can intercept HTTP/HTTPS in code using this library using `ZitiUrlProtocol` (see the main repo README; there are some sample apps in this repo).

If using the SDK directly, this sample app (https://github.com/openziti/ziti-sdk-swift/blob/main/sample-mac-host/main.swift) shows how to use the listen/accept/dial primates, which are similar to using sockets.  The Ziti C-SDK has lower-level functions as part of Ziti_lib that work more directly with sockets, but that still needs to be wrapped by this SDK.

**Comment by smilindave26** [comment]
Is this reply helpful?  Are you willing to share more details about what you're trying to do?

**Comment by five131415** [comment]
> 
Thank you very much for your reply

What I want to achieve is all the traffic of proxy mobile phones, which is the concept of zero trust

If it's android, I can use ziti-sdk-jvm. If it's ios, I can use ziti-tunnel-apple. Is that right?

**Comment by smilindave26** [comment]
Looks like what you want is:
* iPhone: https://apps.apple.com/us/app/ziti-mobile-edge/id1460484353
* Android: https://play.google.com/store/apps/details?id=org.openziti.mobile

These apps are written using the Ziti SDKs and can intercept any network traffic initiated on the phone.
