### ISSUE TITLE
Ziti Mobile Edge crashes

### ISSUE THREAD

**Issue by IT-LiuSir** [openziti/ziti-sdk-swift#193]
iPhone crashes 
When the jwt file is added and cannot be registered, click Enroll This Identity for a third time, the app crashes.
Mac crashes
When there is no jwt file, click the Settings button and adjust the relevant parameters click the OK button, the program crashes.

**Comment by IT-LiuSir** [comment]
iPhone is clicked many times, and the current page stays too long, click again will crash
![image](https://github.com/openziti/ziti-sdk-swift/assets/30195558/1fd58894-dd4b-414a-aacc-64022f86f88d)

**Comment by smilindave26** [comment]
Can you reproduce and send the logs?  You send them in an email by selecting "Send Feedback" from the app (by default this will send the logs to help at openziti dot org.  "app.log" will be the more interesting one in this case.

**Comment by scareything** [comment]
I see what’s happening now. The apple tunnelers call [Ziti.enroll](https://github.com/openziti/ziti-sdk-swift/blob/main/lib/ZitiEnroller.swift#L141) which calls [ziti_enroll](https://github.com/openziti/ziti-sdk-c/blob/main/library/ziti_enroll.c#L81) from the ziti-sdk-c library, and `ziti_enroll` immediately calls [ziti_log_init(https://github.com/openziti/ziti-sdk-c/blob/main/library/utils.c#L144).

The enrollment happens in a different thread than the one that initially called `ziti_log_init`, and the logic there is not prepared to be called from multiple threads. So when `ziti_log_init` is called during enrollment, it is passed a uv_loop that is private to the `Ziti.enroll`. This loop pointer is then assigned to the library's internal loop, and it becomes invalid when `Ziti.enroll` is no longer in scope.

Ultimately `ziti_enroll` should not be concerned with initializing the log functions. That is the responsibility of the calling application (the apple tunnelers in this case). So the likely (and easy!) fix for these crashes will be to simply remove the call to `ziti_log_init`. I've started a branch with that change and I'm testing it in the Apple tunnelers as well as ziti-edge-tunnel.

An update to this repo that pulls in the fixed ziti-sdk-c dependency is forthcoming.
